"use client";

import { useEffect, useState } from "react";
import { getTopicGist, groupByTopic } from "@/lib/summary";
import type { TranscriptItem } from "@/types";
import { generateSummary, getWebLLMState } from "@/lib/ai/webllm-client";
import { cleanSpeechText } from "@/lib/ai/smart-summarizer";

function formatTime(seconds: number) {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60)
    .toString()
    .padStart(2, "0");
  return `${m}:${s}`;
}

/**
 * Owned by the Summaries/Threads feature team (PC4).
 *
 * The whole lesson at a glance — one card per topic with a one-line gist.
 * When the WebGPU LLM is loaded, gists are generated by the real AI model.
 * Otherwise falls back to the local smart summarizer.
 */
export function VisualSummaryTab({
  items,
  currentTime,
  onSeek,
}: {
  items: TranscriptItem[];
  currentTime: number;
  onSeek: (time: number) => void;
}) {
  const byTopic = groupByTopic(items);
  const entries = Object.entries(byTopic);

  // Store LLM-generated gists keyed by topic name
  const [llmGists, setLlmGists] = useState<Record<string, string>>({});

  // Generate gists via WebGPU LLM when available
  useEffect(() => {
    const state = getWebLLMState();
    if (state.status !== "ready" || entries.length === 0) return;

    let cancelled = false;

    for (const [topic, topicItems] of entries) {
      if (llmGists[topic]) continue; // Already generated

      const passage = cleanSpeechText(topicItems.map((i) => i.text).join(" "));
      if (!passage.trim()) continue;

      generateSummary(passage, topic).then((text) => {
        if (!cancelled && text) {
          setLlmGists((prev) => ({ ...prev, [topic]: text }));
        }
      });
    }

    return () => { cancelled = true; };
  }, [entries.length]); // Re-run when topics change

  if (entries.length === 0) {
    return (
      <div className="py-6 text-center text-sm text-zinc-500 dark:text-zinc-400">
        Topic summaries will appear as the lesson progresses.
      </div>
    );
  }

  return (
    <ul className="flex flex-col gap-2">
      {entries.map(([topic, topicItems]) => {
        const start = Math.min(...topicItems.map((item) => item.start));
        const end = Math.max(...topicItems.map((item) => item.end));
        const isActive = currentTime >= start && currentTime < end;

        // Use LLM gist if available, else fall back to local
        const gist = llmGists[topic] ?? getTopicGist(topic, topicItems);

        return (
          <li key={topic}>
            <button
              onClick={() => onSeek(start)}
              className={`w-full rounded-lg border p-3 text-left transition-colors ${
                isActive
                  ? "border-zinc-300 bg-zinc-100 dark:border-zinc-700 dark:bg-zinc-800"
                  : "border-zinc-200 hover:bg-zinc-50 dark:border-zinc-800 dark:hover:bg-zinc-800"
              }`}
            >
              <div className="flex items-baseline justify-between gap-2">
                <span className="text-sm font-medium text-zinc-800 dark:text-zinc-100">
                  {topic}
                </span>
                <span className="shrink-0 text-xs tabular-nums text-zinc-400">
                  {formatTime(start)} – {formatTime(end)}
                </span>
              </div>
              <p className="mt-1 text-xs leading-relaxed text-zinc-500 dark:text-zinc-400">
                {gist}
              </p>
            </button>
          </li>
        );
      })}
    </ul>
  );
}
