import { useEffect, useState } from "react";
import type { CaptionChunk, TranscriptItem } from "@/types";

export type YouTubeCaptionsState =
  | { status: "idle" }
  | { status: "loading" }
  | {
      status: "ready";
      title: string | null;
      duration: number | null;
      autoGenerated: boolean;
      captions: CaptionChunk[];
      items: TranscriptItem[];
    }
  | {
      status: "unavailable";
      title: string | null;
      duration: number | null;
      message: string;
    };

/** Loads the real captions for `videoId` from /api/youtube/captions. */
export function useYouTubeCaptions(videoId: string | null): YouTubeCaptionsState {
  const [result, setResult] = useState<{
    videoId: string;
    state: YouTubeCaptionsState;
  } | null>(null);

  useEffect(() => {
    if (!videoId) return;
    const controller = new AbortController();

    fetch(`/api/youtube/captions?videoId=${encodeURIComponent(videoId)}`, {
      signal: controller.signal,
    })
      .then(async (response) => {
        const body = await response.json();
        setResult({
          videoId,
          state: response.ok
            ? {
                status: "ready",
                title: body.title ?? null,
                duration: body.duration ?? null,
                autoGenerated: Boolean(body.autoGenerated),
                captions: body.captions ?? [],
                items: body.items ?? [],
              }
            : {
                status: "unavailable",
                title: body.title ?? null,
                duration: body.duration ?? null,
                message: body.error ?? "Captions are unavailable for this video.",
              },
        });
      })
      .catch(() => {
        if (controller.signal.aborted) return;
        setResult({
          videoId,
          state: {
            status: "unavailable",
            title: null,
            duration: null,
            message: "Couldn't reach YouTube to load captions.",
          },
        });
      });

    return () => controller.abort();
  }, [videoId]);

  // Derived rather than set in the effect, so switching videos shows
  // "loading" immediately instead of the previous video's captions.
  if (!videoId) return { status: "idle" };
  if (result?.videoId !== videoId) return { status: "loading" };
  return result.state;
}
