import { captionsToLesson, parseTimedText } from "@/lib/video/youtube-captions";

/**
 * GET /api/youtube/captions?videoId=<id>
 *
 * Fetches a YouTube video's caption track server-side (the browser can't:
 * CORS) and returns it in the app's own CaptionChunk/TranscriptItem shapes.
 *
 * The web client's caption URLs now require a proof-of-origin token, but
 * the mobile clients' URLs don't, so the player metadata is requested as
 * those clients. Two are tried in order in case one stops working.
 */

const VIDEO_ID = /^[a-zA-Z0-9_-]{11}$/;
const REQUEST_TIMEOUT_MS = 8000;

const CLIENTS = [
  { clientName: "ANDROID", clientVersion: "20.10.38" },
  { clientName: "IOS", clientVersion: "20.10.4" },
];

interface CaptionTrack {
  baseUrl?: string;
  languageCode?: string;
  kind?: string;
}

/** English manual captions, then English auto-generated, then anything. */
function pickTrack(tracks: CaptionTrack[]): CaptionTrack | undefined {
  const english = tracks.filter((track) => track.languageCode?.startsWith("en"));
  return (
    english.find((track) => track.kind !== "asr") ??
    english[0] ??
    tracks.find((track) => track.kind !== "asr") ??
    tracks[0]
  );
}

function isYouTubeUrl(url: string): boolean {
  try {
    const { protocol, hostname } = new URL(url);
    return protocol === "https:" && (hostname === "youtube.com" || hostname.endsWith(".youtube.com"));
  } catch {
    return false;
  }
}

export async function GET(request: Request) {
  const videoId = new URL(request.url).searchParams.get("videoId") ?? "";
  if (!VIDEO_ID.test(videoId)) {
    return Response.json({ error: "Invalid videoId" }, { status: 400 });
  }

  let title: string | null = null;
  let duration: number | null = null;
  let foundTrack = false;

  for (const client of CLIENTS) {
    try {
      const playerResponse = await fetch(
        "https://www.youtube.com/youtubei/v1/player?prettyPrint=false",
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ context: { client: { ...client, hl: "en" } }, videoId }),
          signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
          cache: "no-store",
        }
      );
      if (!playerResponse.ok) continue;

      const player = await playerResponse.json();
      title ??= player?.videoDetails?.title ?? null;
      const lengthSeconds = Number(player?.videoDetails?.lengthSeconds);
      if (!duration && lengthSeconds > 0) duration = lengthSeconds;

      const tracks: CaptionTrack[] =
        player?.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
      const track = pickTrack(tracks);
      if (!track?.baseUrl || !isYouTubeUrl(track.baseUrl)) continue;
      foundTrack = true;

      const trackResponse = await fetch(track.baseUrl, {
        signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
        cache: "no-store",
      });
      if (!trackResponse.ok) continue;

      const segments = parseTimedText(await trackResponse.text());
      if (segments.length === 0) continue;

      const { captions, items } = captionsToLesson(segments);
      return Response.json({
        videoId,
        title,
        duration,
        language: track.languageCode ?? null,
        autoGenerated: track.kind === "asr",
        captions,
        items,
      });
    } catch (error) {
      console.error(`[api/youtube/captions] ${client.clientName} failed:`, error);
    }
  }

  return Response.json(
    {
      videoId,
      title,
      duration,
      error: foundTrack
        ? "This video has captions, but YouTube wouldn't send them."
        : "This video has no captions available.",
    },
    { status: foundTrack ? 502 : 404 }
  );
}
